Add a ton of shit, now bored

diff --git a/diary b/diary
--- a/diary
+++ b/diary
@@ -1,51 +1,112 @@
 #!/usr/bin/env bash
 
+# set pipefail so that if any command in a pipe fails, the pipe as a whole fails
+set -oe pipefail
+
+DEBUG=1 # Set to 1 to enable debug messages
+LOG=1   # Set to 1 to enable log messages
+
 # Ansi escape colors
 RED='\033[0;31m'
 GREEN='\033[0;32m'
-BLUE='\033[0;34m'
 YELLOW='\033[1;33m'
-PURPLE='\033[0;35m'
+BLUE='\033[0;34m'
+#PURPLE='\033[0;35m' # Not used, but here for reference if needed in the future
 CYAN='\033[0;36m'
 NC='\033[0m'
 
-# Error, warning and success
+# Error, success, info and warning messages
 error() {
-	echo -e "${RED}Error${NC}: ${1}"
+	if [[ -z ${LOG} ]]; then
+		return
+	fi
+	echo -e "[${RED}ERROR${NC}] ${1}"
 }
 
 success() {
-	echo -e "${GREEN}Success${NC}: ${1}"
+	if [[ -z ${LOG} ]]; then
+		return
+	fi
+	echo -e "[${GREEN}SUCCESS${NC}] ${1}"
 }
 
 info() {
-	echo -e "${CYAN}Info${NC}: ${1}"
+	if [[ -z ${LOG} ]]; then
+		return
+	fi
+	echo -e "[${CYAN}INFO${NC}] ${1}"
 }
 
-warning() {
-	echo -e "${YELLOW}Warn${NC}: ${1}"
+debug() {
+	if [[ -z ${DEBUG} ]]; then
+		return
+	fi
+	echo -e "[${BLUE}DEBUG${NC}] ${1}"
 }
+
+warn() {
+	if [[ -z ${LOG} ]]; then
+		return
+	fi
+	echo -e "[${YELLOW}WARNING${NC}] ${1}"
+}
+
+# Trap ctrl-c and call ctrl_c()
+ctrl_c() {
+	echo -e "\nCaught ${GREEN}CTRL-C${NC}, aborting..."
+	exit 1
+}
+
+trap ctrl_c INT
 
 # Preliminary checks
+
 DIARY_DIR="${HOME}/.diary"
+FIND_RESULT=$(find "${DIARY_DIR}" -maxdepth 1 -type d -printf "%f\n" | grep -v "^$(basename "${DIARY_DIR}")$") # Find all diaries in the diary directory
+readarray -t DIARY_LIST <<<"${FIND_RESULT}"                                                                    # Convert the find result to an array
+FZF_INSTALLED=$(command -v fzf)
+
 if [[ ! -d ${DIARY_DIR} ]]; then
-	warning_handler "Diary directory not found, creating one"
+	warn "Diary directory not found, creating one"
+	info "Created diary directory at \"${DIARY_DIR}\""
 	mkdir -p "${DIARY_DIR}"
 fi
 
+# Check if fzf is installed and exit if it isn't
+# fzf is a fuzzy finder used to make selections easier and more user friendly
+# todo: add a flag to disable fzf somehow
+
 # Diary functions
+
+# Create a new diary with the given name (or ask for a name if none is given)
 new_diary() {
-	if [[ -z $2 ]]; then
-		error_handler "No diary name given"
+	if [[ $# -lt 2 ]]; then
+		warn "No diary name given"
 		echo -e -n "${BLUE}Enter diary name${NC}: "
 		read -r DIARY_NAME
 	else
 		DIARY_NAME=$2
 	fi
 
-	local NEW_DIARY="${DIARY_DIR}/${DIARY_NAME}.md"
-	if [[ -f ${NEW_DIARY} ]]; then
-		echo -e "${RED}Diary already exists${NC}"
+	local NEW_DIARY="${DIARY_DIR}/${DIARY_NAME}"
+	if [[ -d ${NEW_DIARY} ]]; then
+		error "Diary already exists at \"${NEW_DIARY}\", please choose a different name"
+		exit 1
+	else
+		if [[ $# -lt 3 ]]; then
+			local info_message='No page name given, using "page1"'
+			PAGE_NAME="page1"
+		else
+			local info_message="Using page name \"${3}\""
+			PAGE_NAME=$3
+		fi
+
+		info "${info_message}"
+		mkdir -p "${NEW_DIARY}"                                     # Create the diary directory
+		mkdir -p "${NEW_DIARY}/pages"                               # Create the pages directory
+		echo -e "# ${PAGE_NAME}\n" >>"${NEW_DIARY}/${PAGE_NAME}.md" # Create the first page and add a title
+		debug "Created page \"${NEW_DIARY}/pages/${PAGE_NAME}.md\""
+		success "Created diary \"${DIARY_NAME}\""
 	fi
 }
 
@@ -53,9 +114,48 @@ default_diary() {
 	echo "default diary"
 }
 
+list_diaries() {
+	if [[ -z ${FZF_INSTALLED} ]]; then
+		RESULT=$(printf "%s\n" "${DIARY_LIST[@]}" | fzf --prompt="Select a diary: ") # Use fzf to select a diary
+	else
+		RESULT="${DIARY_LIST[*]}"
+	fi
+
+	if [[ -z ${RESULT} ]]; then
+		error "No diary selected"
+		exit 1
+	else
+		info "Selected diary \"${RESULT}\""
+		local ACTIONS=("edit" "make default" "rename" "delete")
+		if [[ -v ${FZF} ]]; then
+			ACTION=$(printf "%s\n" "${ACTIONS[@]}" | fzf --prompt="Select an action: ")
+			case ${ACTION} in
+			"edit")
+				edit_diary "${RESULT}"
+				;;
+			"make default")
+				default_diary "${RESULT}"
+				;;
+			"rename")
+				rename_diary "${RESULT}"
+				;;
+			"delete")
+				delete_diary "${RESULT}"
+				;;
+			*)
+				error "Invalid action \"${ACTION}\""
+				exit 1
+				;;
+			esac
+		else
+			ACTION="edit"
+		fi
+	fi
+}
+
 write_help() {
 	echo -e "Usage: $0 [OPTION] [DIARY]"
-	echo -e "Options:"
+	echo -e "Options: \n"
 	echo -e "${RED}new, n, --new, -n,${NC} \t\t |"
 	echo -e "${RED}create, c, --create, -c,${NC} \t |"
 	echo -e "${RED}add, a, --add, -a,${NC} \t\t | \t${CYAN}Creates a new diary with the given name${NC}"
@@ -64,7 +164,8 @@ write_help() {
 	echo -e "\t\t\t\t |"
 	echo -e "${RED}default, d, --default, -d${NC} \t | \t${CYAN}Sets the default diary${NC}"
 	echo -e "\t\t\t\t |"
-	echo -e "${RED}list, ls, --list, -ls${NC} \t\t | \t${CYAN}Lists all diaries${NC}"
+	echo -e "${RED}list, ls, --list, -ls,${NC} \t\t | \t${CYAN}Lists all diaries and allows you to choose${NC}"
+	echo -e "${RED}view, v, --view, -v${NC} \t\t | \t${CYAN}which to rename, edit, delete and make default${NC}"
 	echo -e "\t\t\t\t |"
 	echo -e "${RED}edit, e, --edit, -e${NC} \t\t | \t${CYAN}Edits the given diary (${GREEN}or the default diary if none is given${CYAN})${NC}"
 	echo -e "\t\t\t\t |"
@@ -73,17 +174,18 @@ write_help() {
 	echo -e "${RED}-no${NC} \t\t\t\t |"
 	echo -e "\t\t\t\t |"
 	echo -e "${RED}help, h, --help, -h${NC} \t\t | \t${CYAN}Shows this help message${NC}"
+	echo -e "Optional arguments: \n"
+	echo -e "${RED}--no-fzf, -f${NC} \t\t\t | \t${CYAN}Disables fzf${NC}"
 }
-
 case $1 in
 "new" | "n" | "--new" | "-n" | "create" | "c" | "--create" | "-c" | "add" | "a" | "--add" | "-a" | "make" | "m" | "--make" | "-m" | "-yes")
-	new_diary "${2}"
+	new_diary "${@}"
 	;;
 "default" | "d" | "--default" | "-d")
 	echo "default diary"
 	;;
-"list" | "ls" | "--list" | "-ls")
-	echo "list diaries"
+"list" | "ls" | "--list" | "-ls" | "view" | "v" | "--view" | "-v")
+	list_diaries "${@}"
 	;;
 "edit" | "e" | "--edit" | "-e")
 	echo "edit diary"
